In [ ]:
# Notebook for learning NumPy

In [11]:
# Numpy enabls batch computations of arrays with similar syntax as scalar objects
#  ndarray is a generic multidimensional container for homogenous data
import numpy as np

data = np.array([range(0, 5), range(5, 10)])
print(data)

print(data * 10)

print(data + data)

# shape - tuple indicating the size of each dimension
print(data.shape)

# dtype - object describing the data type of the array
print(data.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0 10 20 30 40]
 [50 60 70 80 90]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
(2, 5)
int64
