In [ ]:
# Notebook for learning NumPy

In [22]:
# Numpy enabls batch computations of arrays with similar syntax as scalar objects
#  ndarray is a generic multidimensional container for homogenous data
import numpy as np

data = np.array([range(0, 5), range(5, 10)])
print(data)

# np.arange() is similar to range function
data2 = np.arange(5)
print(data2)

# Operations between equal-size arrays apply the operation element-wise
print(data * 10)
print(data + data)
print(data - data)
print(data == data)

# shape - tuple indicating the size of each dimension
print(data.shape)

# dtype - object describing the data type of the array
print(data.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[[ 0 10 20 30 40]
 [50 60 70 80 90]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]
(2, 5)
int64


In [20]:
# Specifying dtype
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1)
print(arr2)

# Converting dtypes
arr1 = arr1 + 0.5
print(arr1)
arr1 = arr1.astype(np.int32)
print(arr1)

[1. 2. 3.]
[1 2 3]
[1.5 2.5 3.5]
[1 2 3]


In [34]:
# Slicing -> in contrast with lists, ndarray slices are views of arrays and do not create copies
arr1_slice = arr1[1:4]
print(arr1_slice)
arr1_slice[1] = 5
print(arr1)

# Slicingg 2D arrays
data_slice = data[1]
print(data_slice)
print(data[1,2])
print(data[1:, 2:])
print(data[:1, 2:])
print(data[:2, 2])

[2 5]
[1 2 5]
[5 6 7 8 9]
7
[[7 8 9]]
[[2 3 4]]
[2 7]
